name: Build on Linux

on:
  push:
    branches: [main]
  pull_request:

jobs:

  build:

    name: Build

    runs-on:
      group: fusion-devops-k8s
      labels: fusion-ubuntu
    container:
      image: artifactory.apps.daq.hbm.com/ghcr/qtx-framework-ubuntu-2004

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build project
        uses: threeal/cmake-action@v2.1.0
        with:
          c-compiler: x86_64-unknown-linux-gnu-gcc
          cxx-compiler: x86_64-unknown-linux-gnu-g++
          options: |
            BUILD_SHARED_LIBS=ON
            CMAKE_BUILD_TYPE=Release
            CMAKE_INSTALL_LIBDIR=lib
            CMAKE_INSTALL_PREFIX=/usr
            HBK_GENERATE_DOC=ON
            HBK_TOOLS=ON
            HBK_HARDWARE=OFF
