name: Build on Windows

on:
  push:
    branches: [main]
  pull_request:

jobs:

  build:

    name: Build

    runs-on:
      group: fusion-devops-windows

    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build project
        uses: threeal/cmake-action@v2.1.0
        with:
          options: |
            BUILD_SHARED_LIBS=ON
            HBK_GENERATE_DOC=ON
            HBK_TOOLS=ON
            HBK_HARDWARE=OFF
